## User

### Login
POST http://127.0.0.1:8624/api/users/login
content-type: application/json

{
    "username" : "30WPP",
    "password": "FR4BYQA"
}
### Login(GET)
GET http://127.0.0.1:8000/api/login

### Casual
GET http://127.0.0.1:8000/api/casual

### Login(OPTIONS)
OPTIONS http://127.0.0.1:8000/api/login
